#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<conio.h>
#include"fonctions2.0.c"
main(){
	   	 client *x;
	   	 voiture *v;
	   	 location *a;
	   	 char marque1[20],type1[20],ville1[20],nom1[20],lettre1[1],w[15];
	   	 date d;
	   	 int n,r,pc,pv,pl,cin1,matricule1,mat1,duree,CIN1,choix,choix1,choix2,choix3;
	   	//system("color 7f");
        do{
        printf("\033[1;31m");
        printf("\n\n\t\t\t\t\t<============================================================================>\n\n");
        printf("\033[1;35m");
	    printf("\033[%dC", (int)((80 - strlen("----------------> BIENVENUE <----------------")) / 2));
	    printf("\t\t\t\t\t\033[3m----------------> BIENVENUE <----------------\033[0m\n\n"); 
	    printf("\033[0m");
	    printf("\033[1;32m");
	    printf("\033[%dC", (int)((80 - strlen("CHEZ AGENCE NGN DE LOCATION DE VOITURE")) / 2)); 
	    printf("\t\t\t\t\t\033[3m|-->CHEZ AGENCE NGN DE LOCATION DE VOITURE<--|\033[0m\n"); 
	    printf("\033[0m");
        printf("\033[1;34m");
printf("\n\t\t\t\t\t               \xc9\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbb");
	printf("\n\t\t\t\t\t               \xba                                             \xba");
	printf("\n\t\t\t\t\t               \xba       ajout..........................1      \xba");
	printf("\n\t\t\t\t\t               \xba       affichage......................2      \xba");
	printf("\n\t\t\t\t\t               \xba       supression.....................3      \xba");
	printf("\n\t\t\t\t\t               \xba       Quitter........................4      \xba");
	printf("\n\t\t\t\t\t               \xba                                             \xba");
	printf("\n\t\t\t\t\t               \xba                                             \xba");
	printf("\n\t\t\t\t\t               \xc8\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbc");
	printf("\033[1;33m");
	printf("\n\n\t\t\t\t\t                                Votre choix  :  ");
    scanf("%d",&choix);
	printf("\033[1;31m");
	system("pause");
	system("cls");
	printf("\033[0m");
	 switch (choix){
	case 1: printf("\033[1;31m");
	        printf("\n\n\t\t\t\t\t<============================================================================>\n\n");
	        printf("\033[1;35m");
	                 {printf("\n\t\t\t\t\t                \xc9\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbb");
			printf("\n\t\t\t\t\t                \xba                                              \xba");
			printf("\n\t\t\t\t\t                \xba    ajoute_client.........................1   \xba");
			printf("\n\t\t\t\t\t                \xba    ajoute_voiture........................2   \xba");
			printf("\n\t\t\t\t\t                \xba    ajoute_location.......................3   \xba");
			printf("\n\t\t\t\t\t                \xba    ajouter_client_a_pos..................4   \xba");
			printf("\n\t\t\t\t\t                \xba    ajouter_voiture_a_pos.................5   \xba");
			printf("\n\t\t\t\t\t                \xba    ajouter_location_a_pos................6   \xba");
			printf("\n\t\t\t\t\t                \xba    Retour au meunu principal.............7   \xba");
			printf("\n\t\t\t\t\t                \xba                                              \xba");
			printf("\n\t\t\t\t\t                \xc8\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbc");
			printf("\033[0m");
			printf("\033[1;33m");
			printf("\n\n\n\t\t\t\t\t                                 Votre choix  :  "); ;
		    scanf("%d",&choix1);
		    	system("pause");
            	system("cls");
            printf("\033[0m");
			printf("\033[1;32m");	
	    switch (choix1){ 
		    case 1: printf("\t\t\t==> SAISIR LE NOMBRE DES CLIENTS : \t"); 
		            scanf("%d",&n); 
		            x=(client*) malloc (n*sizeof(client));
			        ajoute_client (x,n);
			        printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
			      break; 
		    case 2:  printf("\t\t\t==> SAISIR LE NOMBRE DES VOITURES : \t"); 
		             scanf("%d",&n); 
			         v=(voiture*) malloc (n*sizeof(voiture));
			         ajoute_voiture(v,n);
		             printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
		          break;
		    case 3: printf("\t\t\t==> SAISIR LE NOMBRE DES LOCATIONS : \t"); 
		            scanf("%d",&n); 
			        a=(location*) malloc (n*sizeof(location));
			        ajoute_location(a,n); 
		            printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
		    case 4: printf("\t\t\t==> SAISIR LA POSITION SOUHAITEE :  ");
   	                scanf("%d",&pc);
   	                ajouter_client_a_pos(x,pc,n);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
			case 5:printf("\t\t\t==> SAISIR LA POSITION SOUHAITEE :  ");
   	               scanf("%d",&pv);
   	               ajouter_voiture_a_pos(v,pv,n);
   	               printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			       scanf("%d",&r);
   	               system("cls");
		          break;
		    case 6: printf("\t\t\t==> SAISIR LA POSITION SOUHAITEE :  ");
   	                scanf("%d",&pl);
   	                ajouter_location_a_pos(a,pl,n);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;     
			case 7: system("cls");break;
			default: printf("\033[31m");
			         printf("\t\t\t==> Erreur, veuillez appuyer sur 0 pour retourner vers le menu principal !!\n");
			         scanf("%d",&choix1);break;}
			         system("cls");
			   break;}
			   printf("\033[0m");
		
    case 2:  {printf("\033[1;31m");
	          printf("\n\n\t\t\t\t\t<======================================================================>\n\n");
	          printf("\033[1;36m");
	        printf("\n\t\t\t\t                \xc9\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbb");
			printf("\n\t\t\t\t                \xba                                                       \xba");
			printf("\n\t\t\t\t                \xba    afficherToutesLesVoitures......................1   \xba");
			printf("\n\t\t\t\t                \xba    afficherVoituresParMarque......................2   \xba");
			printf("\n\t\t\t\t                \xba    afficherVoituresPartype........................3   \xba");
			printf("\n\t\t\t\t                \xba    afficherToutesLesclients.......................4   \xba");
			printf("\n\t\t\t\t                \xba    afficherclientsParville........................5   \xba");
			printf("\n\t\t\t\t                \xba    afficherclientsParCin..........................6   \xba");
			printf("\n\t\t\t\t                \xba    afficherlocationParnom.........................7   \xba");
			printf("\n\t\t\t\t                \xba    afficherlocationParvoiture.....................8   \xba");
			printf("\n\t\t\t\t                \xba    afficherlocationParduree.......................9   \xba");
			printf("\n\t\t\t\t                \xba    afficherlocationParddl.........................10  \xba");
			printf("\n\t\t\t\t                \xba    afficher_clients_par_lettre....................11  \xba");
			printf("\n\t\t\t\t                \xba    afficherlechiffre..............................12  \xba");
			printf("\n\t\t\t\t                \xba    compter_contacts_ville.........................13  \xba");
			printf("\n\t\t\t\t                \xba    afficherlesinformationchiffre..................14  \xba");
			printf("\n\t\t\t\t                \xba    Retour au meunu principal......................15  \xba");
			printf("\n\t\t\t\t                \xba                                                       \xba");
			printf("\n\t\t\t\t                \xc8\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbc");
			printf("\033[33m");
			printf("\n\n\n\t\t\t\t                                Votre choix  :  "); ;
		    scanf("%d",&choix2);
		    	system("pause");
	            system("cls");
	            printf("\033[1;32m");
	switch (choix2){ 
		    case 1: afficherToutesLesVoitures(v,n);
		            printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
			      break; 
		    case 2:  puts("\t\t\t==> SAISIR LA MARQUE SOUHAITEE :  ");
   	                 scanf("%s",&marque1);
   	                 fflush(stdin);
   	                 afficherVoituresParMarque(v,n,marque1);
   	                 printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
		          break;
		    case 3: puts("\t\t\t==> SAISIR LE TYPE SOUHAITEE :  ");
   	                scanf("%s",&type1);
   	                fflush(stdin);
   	                afficherVoituresPartype(v,n,type1);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
		    case 4: afficherToutesLesclients(x,n);
		            printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
			case 5: puts("\t\t\t==> SAISIR LA VILLE SOUHAITEE :  ");
   	                scanf("%s",&ville1);
   	                fflush(stdin);
   	                afficherclientsParville(x,n,ville1);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
		    case 6: printf("\t\t\t==> SAISIR LE CIN SOUHAITEE :  ");
   	                scanf("%d",&cin1);
   	                afficherclientsParCin(x,n,cin1);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
			case 7: puts("\t\t\t==> SAISIR LE NOM SOUHAITEE POUR AFFICHER LA LOCATION :  ");
   	                scanf("%s",nom1);
   	                fflush(stdin);
   	                afficherlocationParnom(x,a,n,nom1);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
			case 8: printf("\t\t\t==> SAISIR LE MATRICULR SOUHAITEE :  ");
   	                scanf("%d",&matricule1);
   	                afficherlocationParvoiture(v,a,n,matricule1);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
			case 9: printf("\t\t\t==> SAISIR LA DUREE SOUHAITEE :  ");
   	                scanf("%d",&duree);
   	                afficherlocationParduree(a,n,duree);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;	  	
			case 10: do{
                        printf("\t\t\t==> SAISIR LA DATE SOUHAITEE : (jj/mm/aaaa)  : ");
                        scanf("%d/%d/%d",&d.jj,&d.mm,&d.aa); 
                    }while(d.jj<1||d.jj>31||d.mm<1||d.mm>12||d.aa<1930||d.aa>2030);
   	                afficherlocationParddl(a,n,d);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		          break;
			case 11: printf("\t\t\t==> SAISIR LA LETTRE SOUHAITEE :  ");
   	                 scanf("%s",&lettre1);
   	                 afficher_clients_par_lettre(x,n,lettre1);
   	                 printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
		          break;
			case 12: printf("\t\t\t==> DONNER LE MATRICULE : ");
                     scanf("%d",&mat1);
   	                 afficherlechiffre(v,a,n,mat1);
   	                 printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
			      break; 
			case 13: compter_contacts_ville(x,n,w);
			         printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
			      break; 
			case 14: afficherlesinformationchiffre(v,a,n);
			         printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
			      break; 	  	  	  	  	    	        
			case 15: system("cls");break;  
            break;
           default: printf("\033[31m");
		            printf("\t\t\t==> Erreur, veuillez appuyer sur 0 pour retourner vers le menu principal !!\n");
                    scanf("%d",&choix2);
                    break;}
            printf("\033[0m");
			system("cls");        
            break;}
	case 3: {printf("\033[1;31m");
	        printf("\n\n\t\t\t\t\t<============================================================================>\n\n");
	        printf("\033[35m");
	         printf("\n\t\t\t\t\t               \xc9\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbb");
			printf("\n\t\t\t\t\t               \xba                                              \xba");
			printf("\n\t\t\t\t\t               \xba    supprimerClient.......................1   \xba");
			printf("\n\t\t\t\t\t               \xba    supprimerVoiture......................2   \xba");
			printf("\n\t\t\t\t\t               \xba    supprimercontact......................3   \xba");
			printf("\n\t\t\t\t\t               \xba    Retour au meunu principal.............4   \xba");
			printf("\n\t\t\t\t\t               \xba                                              \xba");
			printf("\n\t\t\t\t\t               \xc8\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xcd\xbc");
			printf("\033[1;33m");
			printf("\n\n\t\t\t\t\t                                Votre choix  :  "); ;
		    scanf("%d",&choix3);
		    	system("pause");
	            system("cls");
	            printf("\033[1;32m");
		    switch (choix3){ 
			case 1:  printf("\t\t\t==> CIN du client a supprimer : ");
                     scanf("%d",&CIN1);
   	                 supprimerClient(x,n,CIN1);
   	                 printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
			      break; 
		    case 2:  printf("\t\t\t==> Numero d'immatriculation de la voiture a supprimer : ");
                     scanf("%d",&matricule1);
   	                 supprimerVoiture(v,&n,matricule1);
   	                 printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			         scanf("%d",&r); 
			         system("cls");
		          break;
		    case 3: printf("\t\t\t==> la ville a supprimer les contact : ");
                    scanf("%s",&w);
                    fflush(stdin);
   	                supprimercontact(x,n,w);
   	                printf("\n\t\t\t=====> SAISIR 0 POUR RETOURNER VERS LE MENU PRINCIPAL : \t"); 
			        scanf("%d",&r); 
			        system("cls");
		            break;
		    case 4: system("cls");break; 
			default:printf("\033[31m"); 
			        printf("\t\t\t==> Erreur, veuillez appuyer sur 0 pour retourner vers le menu principal !!\n");
			        scanf("%d",&choix3);
                    break;} 
                    system("cls");  
                      break;}
			printf("\033[0m");
	case 4 :{
	        printf("\033[1;31m");
            printf("\n\t\t\t\t\t<============================================================================>\n\n");
            printf("\033[1;32m");
		    printf("\033[%dC", (int)((80 - strlen("\t\t\t\t\t\tAGENCE NGN DE LOCATION DE VOITURE!!")) / 2)); 
		    printf("\033[3m\t\t\t\t\t\tAGENCE NGN DE LOCATION DE VOITURE\033[0m\n\n"); 
		    printf("\033[0m");
		    printf("\033[1;35m");
		    printf("\033[%dC", (int)((80 - strlen("----------------> AU REVOIR <----------------")) / 2)); 
		    printf("\033[3m\t\t\t\t\t-----------------> AU REVOIR <-----------------\033[0m\n"); 
		    printf("\033[0m");
	        printf("\033[1;34m");	
	        printf("\033[0m");exit(0);break;}
	        break;}
			printf("\033[1;32m");
           	}while(choix1==7||choix3==4||choix2==15||r==0||choix!=1||choix!=2||choix!=3||choix!=4);
	getch();
	}
